export default {
  users: [
    {
      userId: 1,
      email: 'test1@gmail.com',
      password: '123123',
      nickname: 'User1',
      name: '송진영',
      phone: '010-1234-5678',
      avartarUrl: './img.jpg',
    },
    {
      userId: 2,
      email: 'test2@gmail.com',
      password: '234234',
      nickname: 'User2',
      name: '김민성',
      phone: '010-2345-6789',
      avartarUrl: './img.jpg',
    },
    {
      userId: 3,
      email: 'test3@gmail.com',
      password: '345345',
      nickname: 'User3',
      name: '안현서',
      phone: '010-3456-7890',
      avartarUrl: './img.jpg',
    },
    {
      userId: 4,
      email: 'test4@gmail.com',
      password: '456456',
      nickname: 'User4',
      name: '원종빈',
      phone: '010-4567-8901',
      avartarUrl: './img.jpg',
    },
  ],

  posts: [
    {
      postId: 1,
      userId: 1,
      title: '제목1',
      content: '내용1',
      imgUrl: ['./img.jpg', './img2.jpg'],
      createAt: '2021-01-10',
    },
    {
      postId: 5,
      userId: 1,
      title: '제목1',
      content: '내용1',
      imgUrl: ['./img.jpg', './img2.jpg'],
      createAt: '2021-01-10',
    },
    {
      postId: 6,
      userId: 1,
      title: '제목1',
      content: '내용1',
      imgUrl: ['./img.jpg', './img2.jpg'],
      createAt: '2021-01-10',
    },
    {
      postId: 7,
      userId: 1,
      title: '제목1',
      content: '내용1',
      imgUrl: ['./img.jpg', './img2.jpg'],
      createAt: '2021-01-10',
    },
    {
      postId: 8,
      userId: 1,
      title: '제목1',
      content: '내용1',
      imgUrl: ['./img.jpg', './img2.jpg'],
      createAt: '2021-01-10',
    },
    {
      postId: 2,
      userId: 2,
      title: '제목2',
      content: '내용2',
      imgUrl: ['./img.jpg', './img2.jpg'],
      createAt: '2021-01-10',
    },
    {
      postId: 3,
      userId: 3,
      title: '제목3',
      content: '내용3',
      imgUrl: ['./img.jpg', './img2.jpg'],
      createAt: '2021-01-10',
    },
    {
      postId: 4,
      userId: 4,
      title: '제목4',
      content: '내용4',
      imgUrl: ['./img.jpg', './img2.jpg'],
      createAt: '2021-01-10',
    },
  ],
};
